# Application name
spring.application.name=Ceylon-Harvest-Capital

# PostgreSQL connection (Supabase)
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.rmihwiomlmvisdwzoubs
spring.datasource.password=uccUrjjSffaasOnj
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=8080
server.address=0.0.0.0
server.compression.enabled=false

# MVC / Async
spring.mvc.async.request-timeout=5000

# JWT
jwt.secret=Ly8gUnVuIHRoaXMgb25jZSwgY29weSB0aGUgb3V0cHV0LCBwYXN0ZSBpbnRvIGFwcGxpY2F0aW9uLnByb3BlcnRpZXMKYnl0ZVtdIGtleSA9IEtleXMuc2VjcmV0S2V5Rm9yKFNpZ25hdHVyZUFsZ29yaXRobS5IUzI1NikuZ2V0RW5jb2RlZCgpOwpTeXN0ZW0ub3V0LnByaW50bG4oQmFzZTY0LmdldEVuY29kZXIoKS5lbmNvZGVUb1N0cmluZyhrZXkpKTs=
jwt.expiration=3600000

# Default system admin — created automatically on startup
admin.default.email=admin@chc.com
admin.default.password=Admin@CHC2026
admin.default.fullName=System Admin

# Google Service (use dummy values)
google.client.id=TEST_GOOGLE_CLIENT_ID
google.client.secret=TEST_GOOGLE_CLIENT_SECRET

# Polygon Amoy Testnet (dummy key for push)
blockchain.rpc.url=https://rpc-amoy.polygon.technology
blockchain.wallet.privateKey=TEST_PRIVATE_KEY
blockchain.polygonscan.url=TEST_POLYGONSCAN_URL

# Blockchain system wallet
blockchain.wallet.address=TEST_WALLET_ADDRESS
blockchain.rpc.url=https://rpc-amoy.polygon.technology